#FROM daocloud.io/x3193/cd-opsv3:master-2149b4e
#FROM daocloud.io/x3193/cd-opsv3:master-150cc36
FROM daocloud.io/x3193/cd-opsv3:master-8e4900d

#RUN sh /var/www/html/shell/cloud/opsv3/opsv3.sh full 1067550000 trusty x3193;
RUN sh /var/www/html/shell/cloud/opsv3/opsv3.sh full 1067550000 xenial x3193;

USER 1067550000

#CMD /ops-run.sh full
#CMD /ops-run.sh full opsv3
